Mysql:
  Host: 127.0.0.1
  Port: 33309
  Usr: root
  Pwd: root
  Database: polaris_project_manage_appsvc_lctest
Redis:
  Database: 4
Logs:
  Default:
    LogPath: ./run.log
    Level: debug
  RR:
    LogPath: ./rr.log
    Level: info
  MQ:
    LogPath: ./mq.log
    Level: info
Parameters:
  EsIndex:
    Issue: issue_index_test
    Project: project_index_test
    Trends: trends_index_test