Server:
  # 程序启动端口
  Port: 8181
  # 应用名
  Name: Nico
  # 前端应用地址
  Domain: 127.0.0.1
Mysql:
  Host:
  Port:
  Usr:
  Pwd:
  Database:
  MaxOpenConns: 500
  MaxIdleConns: 30
Redis:
  Host: 127.0.0.1
  Port:
  Pwd:
  Database: 4
  MaxIdle: 20
  MaxActive: 200
  MaxIdleTimeout: 3600
# 邮件配置，目前暂未使用
Mail:
  Alias: 极星协作
  Usr:
  Pwd:
  Host:
  Port:
# 应用配置
Application:
  # 应用名
  Name: polaris-backend
  # 运行模式，1：Saas集群，2：单机部署，3：私有化集群部署，4：私有化单库部署
  RunMode: 1
  # 缓存模式
  CacheMode: Redis
Logs:
  # 默认日志配置
  Default:
    # 日志路径
    LogPath: ./run.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 是否写入kafka
    EnableKafka: false
    #写入kafkatopic
    KafkaTopic: :appName:_Logs
    # kafka 服务地址
    KafkaNameServers: 192.168.1.152:9092
    # 标签
    Tag: run
  # 输入输出日志
  RR:
    # 日志路径
    LogPath: ./rr.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: false
    # 单个日志文件大小
    MaxSize: 1024
    # 保留日志文件数
    FileNum: 20
    # 是否写入kafka
    EnableKafka: false
    # 写入kafkatopic
    KafkaTopic: :appName:_Logs
    # kafka 服务地址
    KafkaNameServers: 192.168.1.152:9092
    # 标签
    Tag: rr
  # 消息队列日志
  MQ:
    LogPath: ./mq.log
    Level: info
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    FileNum: 20
    # 是否写入kafka
    EnableKafka: false
    # 写入kafkatopic
    KafkaTopic: :appName:_Logs
    # kafka 服务地址
    KafkaNameServers: 192.168.1.152:9092
    # 标签
    Tag: mq
  DingTalkLogBot:
    LogPath: https://oapi.dingtalk.com/robot/send?access_token=702cfb2109b3b44e97aa2024bb403bf94a04bb16e22fb3116adbf9bfa8e13349
    # 标签
    Tag: dingTalkLogBot
# 消息队列日志
MQ:
  Mode: Kafka
  Kafka:
    NameServers: 192.168.1.152:9092
    #    NameServers: 192.168.1.181:9092
    #    NameServers: 192.168.1.210:30092
    # 推送失败重新消费的次数
    ReconsumeTimes: 3
  Topics:
    IssueTrends:
      Topic: topic_issue_trends
      GroupId: topic_issue_trends_group
    ProjectTrends:
      Topic: topic_project_trends
      GroupId: topic_project_trends_group
    DailyProjectReportProject:
      Topic: topic_project_report_project
      GroupId: topic_project_report_group
    DailyProjectReportMsg:
      Topic: topic_project_report_msg
      GroupId: topic_project_report_msg_group
    IssueRemind:
      Topic: topic_issue_remind
      GroupId: topic_issue_remind_group
    ImportIssue:
      Topic: topic_import_issue
      GroupId: topic_import_issue_group
    OrgMemberChange:
      Topic: topic_org_member_change
      GroupId: topic_org_member_change_group
    SyncMemberDept:
      Topic: topic_org_sync_member_dept_local
      GroupId: topic_org_sync_member_dept_group_local
    FeiShuCallBack:
      Topic: topic_feishu_callback
      GroupId: topic_feishu_callback_group
    HelpMessagePushToFeiShu:
      Topic: topic_help_message_push_to_feishu
      GroupId: topic_help_message_push_to_feishu_group
    DailyTaskPushToFeishu:
      Topic: topic_daily_task_push_to_feishu
      GroupId: topic_daily_task_push_to_feishu_group
    StatisticIterationBurnDownChart:
      Topic: topic_statistic_iteration_burn_down_chart
      GroupId: topic_statistic_iteration_burn_down_chart_group
    StatisticProjectIssueBurnDownChart:
      Topic: topic_statistic_project_issue_burn_down_chart
      GroupId: topic_statistic_project_issue_burn_down_chart_group
    FeiShuEntranceRemind:
      Topic: topic_feishu_entrance_remind
      GroupId: topic_feishu_entrance_remind_group
    ThirdSourceChannelOrder:
      Topic: topic_third_source_channel_order
      GroupId: topic_third_source_channel_order_group
    FeiShuCallBackMsg:
      Topic: topic_feishu_callback_msg
      GroupId: topic_feishu_callback_msg_group
    FeiShuCallBackOrder:
      Topic: topic_feishu_callback_order
      GroupId: topic_feishu_callback_order_group
    FeishuShortcut:
      Topic: topic_feishu_shortcut
      GroupId: topice_feishu_shortcut_group
    FeishuShortcutPush:
      Topic: topic_feishu_shortcut_push
      GroupId: topice_feishu_shortcut_push_group
    FeishuCommonMsgPush:
      Topic: topic_feishu_common_msg_push
      GroupId: topic_feishu_common_msg_push_group
    FeishuCallBackContactScopeChange:
      Topic: topic_feishu_callback_contact_scope_change
      GroupId: topic_feishu_callback_contact_scope_change_group
    FeishuCallBackUserChange:
      Topic: topic_feishu_callback_user_change
      GroupId: topic_feishu_callback_user_change
    FeishuSurveyNotice1123Push:
      Topic: topic_feishu_survey_notice_1123_push
      GroupId: topic_feishu_survey_notice_1123_push_group
    RemindUsingToNewUser:
      Topic: topic_feishu_remind_using_to_new_user_topic
      GroupId: topic_feishu_remind_using_to_new_user_group
    FeishuDynCommonMsgPush:
      Topic: topic_dyn_feishu_common_msg_push
      GroupId: topic_dyn_feishu_common_msg_push_group
# ES 配置，目前暂未使用
ElasticSearch:
  #es 服务地址
  ServerUrls: [ "http://192.168.1.152:9200" ]
  # 是否进行节点嗅探
  Sniff: false
  # 超时时间，毫秒
  Timeout: 1000
  Auth:
    UserName: ""
    Password: ""
# 参数配置
Parameters:
  # 分隔符
  CodeConnector: '#'
  # id生成阈值
  IdBufferThreshold: 0.6
  # 最大分页数量
  MaxPageSize: 100
  # es索引名
  EsIndex:
    Issue: issue_index_dev
    Project: project_index_dev
    Trends: trends_index_dev
  # 服务访问前缀
  PreUrl:
    idsvc: http://127.0.0.1:10002
    msgsvc: http://127.0.0.1:10003
    appsvc: http://127.0.0.1:10001
    commonsvc: http://127.0.0.1:10005
    app: http://127.0.0.1:12000
    orgsvc: http://127.0.0.1:12001
    projectsvc: http://127.0.0.1:12002
    processsvc: http://127.0.0.1:12003
    resourcesvc: http://127.0.0.1:120041
    noticesvc: http://127.0.0.1:12005
    rolesvc: http://127.0.0.1:12006
    callsvc: http://127.0.0.1:12007
    trendssvc: http://127.0.0.1:12008
    websitesvc: http://127.0.0.1:12011
    compatsvc: http://127.0.0.1:8000
    ordersvc: http://127.0.0.1:12012
    usercentersvc: http://127.0.0.1:15001
    lesscodedatacentersvc: http://172.19.132.103:10675
    smssvc: http://bff-test.startable.cn

# 阿里云OSS配置
OSS:
  BucketName:
  EndPoint:
  AccessKeyId:
  AccessKeySecret:
  RootPath: /data/resources/polaris
  LocalDomain: http://127.0.0.1:12010
  Policies:
    ProjectCover:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/cover/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
    IssueResource:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/issue_{{.issueId}}/resource/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
      CallbackUrl: http://polarisfs-local.vaiwan.com/api/callsvc/callback/oss/policy
    LesscodeResource:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/issue_{{.issueId}}/lesscode_resource/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
      CallbackUrl: http://polarisfs-local.vaiwan.com/api/callsvc/callback/oss/policy
    IssueInputFile:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/input_issues/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
    ProjectResource:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/resource/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
      CallbackUrl: http://polarisfs-local.vaiwan.com/api/callsvc/callback/oss/policy
    CompatTest:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/compat_test/apk/{{.year}}/{{.month}}/{{.day}}
      # 512M
      MaxFileSize: 536870912
    UserAvatar:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/folder_resource/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
    Feedback:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/feedback_resource/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
    IssueRemark:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/project_{{.projectId}}/issue_{{.issueId}}/IssueRemark/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
    ImportMembers:
      BucketName: polaris-hd2
      Expire: 300000
      Dir: org_{{.orgId}}/org/{{.year}}/{{.month}}/{{.day}}
      MaxFileSize: 10485760
# SkyWalking
#SkyWalking:
#  ReportAddress: 106.15.190.190:11820
SMS:
  AccessKeyId:
  Region:
  AccessKeySecret:
# MQTT
MQTT:
  Address: wss://mqtt.domain.cn:443
  # 重复配置是因为要返给前端
  Host: mqtt.domain.cn
  Port: 443
  SecretKey:
  Enable: true
  ConnectPoolSize: 20
yidun:
  api:
  version:
  captchaId:
  secretId:
  secretKey:
