Mysql:
#  Host: 127.0.0.1
#  Port: 33309
#  Usr: root
#  Pwd: root
  # 数据库库名
  Database: polaris_project_manage_orgsvc_lctest
Logs:
  Default:
    LogPath: ./run.log
  RR:
    LogPath: ./rr.log
  MQ:
    LogPath: ./mq.log