Server:
  Port: 10002
Logs:
  # 默认日志配置
  Default:
    LogPath: /data/logs/polaris-idsvc/run.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: run
  # 输入输出日志
  RR:
    LogPath: /data/logs/polaris-idsvc/rr.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: false
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: rr
  # 消息队列日志
  MQ:
    LogPath: /data/logs/polaris-idsvc/mq.log
    # 日志级别
    Level: info
    # 控制台是否输出
    IsConsoleOut: true
    # 单个日志文件大小
    FileSize: 1024
    # 保留日志文件数
    MaxBackups: 20
    # 标签
    Tag: mq

Application:
  Name: idsvc
  Version:
Sentry:
  Dsn: https://127.0.0.1/7

Mysql:
  Host: 127.0.0.1
  Port: 33309
  Usr: root
  Pwd: root
  # 数据库库名
  Database: polaris_project_manage_idsvc_lctest
Redis:
  Host: 127.0.0.1
  Port:
  Pwd:
  Database: 4
  MaxIdle: 20
  MaxActive: 200
  MaxIdleTimeout: 3600
Parameters:
  # id生成阈值
  IdBufferThreshold: 0.6